package nbaquery.data;

import java.util.Collection;

import nbaquery.data.query.Query;

public interface TableHost
{
	public Table getTable(String tableName);
	
	public Column getColumn(String columnName);
	
	/**
	 * <b>Warning: </b> only tables generated by perform query could be deleted!
	 * @param tableName the table to delete.
	 */
	public void deleteTable(String tableName);
	
	public void performQuery(Query query, String tableName);
	
	public Collection<DirtyDataInfo> getDirtyDataInfo();
}
